name: matricmate
description: "MatricET — Ethiopian matric exam prep app with chapter tests, entrance exams, bookmarks, and offline support."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.1+2

environment:
  sdk: ^3.10.0
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  http: ^1.6.0
  get_storage: ^2.1.1
  intl: ^0.20.2
  get: ^4.7.3
  connectivity_plus: ^7.1.0
  smooth_page_indicator: ^2.0.1
  sqflite: ^2.4.2
  path: ^1.9.1
  supabase_flutter: ^2.12.2
  flutter_secure_storage: ^10.0.0
  uuid: ^4.5.3
  image_picker: ^1.2.1
  flutter_cache_manager: ^3.4.1
  iconsax_flutter: ^1.0.1
  fluttertoast: ^10.0.0
  shared_preferences: ^2.3.2
  flutter_dotenv: ^5.1.2
  flutter_local_notifications: ^22.2.0

  firebase_core: ^4.14.0

  url_launcher: ^6.3.1
  google_fonts: ^6.2.1
  firebase_messaging: ^16.4.3
  share_plus: ^13.3.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/adaptive_foreground.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/subjects/
    - assets/images/profile/
    - assets/images/logo/
    - assets/icons/
