// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4mzPQDk1KnTs2vYKheKQl3zDu6TBnSv0',
    appId: '1:768230513418:web:381e6ac6d3ece5978178f3',
    messagingSenderId: '768230513418',
    projectId: 'matricmate-a1bf6',
    authDomain: 'matricmate-a1bf6.firebaseapp.com',
    storageBucket: 'matricmate-a1bf6.firebasestorage.app',
    measurementId: 'G-HRLHSFVRPX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_MNqrCLJcvbyT28mXTWoeB7MNfFXEKvM',
    appId: '1:768230513418:android:c86fc2d489f25b878178f3',
    messagingSenderId: '768230513418',
    projectId: 'matricmate-a1bf6',
    storageBucket: 'matricmate-a1bf6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwfRHpMue0NvQ010s4lAd-1GMJTdj7ci8',
    appId: '1:768230513418:ios:2f88188a0910331d8178f3',
    messagingSenderId: '768230513418',
    projectId: 'matricmate-a1bf6',
    storageBucket: 'matricmate-a1bf6.firebasestorage.app',
    iosBundleId: 'com.example.matricmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwfRHpMue0NvQ010s4lAd-1GMJTdj7ci8',
    appId: '1:768230513418:ios:2f88188a0910331d8178f3',
    messagingSenderId: '768230513418',
    projectId: 'matricmate-a1bf6',
    storageBucket: 'matricmate-a1bf6.firebasestorage.app',
    iosBundleId: 'com.example.matricmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4mzPQDk1KnTs2vYKheKQl3zDu6TBnSv0',
    appId: '1:768230513418:web:45021a0bc4a446798178f3',
    messagingSenderId: '768230513418',
    projectId: 'matricmate-a1bf6',
    authDomain: 'matricmate-a1bf6.firebaseapp.com',
    storageBucket: 'matricmate-a1bf6.firebasestorage.app',
    measurementId: 'G-VLZERBJFRE',
  );
}
