-- =====================================================================
-- 0001_admin_foundation.sql
--
-- Foundation for the MatricMate admin console.
--
-- SAFETY CONTRACT
--   * Idempotent: every statement uses IF NOT EXISTS / IF EXISTS or is
--     wrapped in a DO block that checks first. Safe to run repeatedly.
--   * Non-destructive: no DROP, no ALTER ... TYPE, no data rewrite of any
--     existing column. Only additive DDL plus backfills of columns this
--     migration itself creates.
--   * Additive to a LIVE database that already contains users,
--     payment_receipts, notifications, user_sessions, subjects, chapters,
--     tests, questions, passages and question_sections.
--
-- TWO FACTS THAT SHAPE EVERY DECISION BELOW
--
--   1. users.id is a FIREBASE UID (text), not an auth.uid() uuid.
--      lib/data/repositories/user/user_repository.dart keys every query on
--      the Firebase UID, while lib/data/services/ensure_supabase_auth.dart
--      signs the client in ANONYMOUSLY. The Supabase JWT subject and
--      users.id are therefore unrelated values. Any policy written as
--      `auth.uid() = id` would lock the entire student app out. All admin
--      identity columns below are text for the same reason.
--
--   2. Most of the student app talks to Postgres as `anon`.
--      ensure_supabase_auth() is called ONLY from user_repository and
--      payment_repository. The sync, notification and session repositories
--      make no session at all. So this migration must not enable RLS on any
--      table the student app already reads. It enables RLS only on the four
--      tables it creates, all of which the student app never touches except
--      notification_reads (insert-only, see §8).
-- =====================================================================

BEGIN;


-- =====================================================================
-- 1. ADMIN IDENTITY
-- =====================================================================
-- firebase_uid is the PK because Firebase Auth remains the identity
-- provider, exactly as in the student app. email is the lookup key used by
-- is_admin(), because that is the claim the admin-auth edge function can
-- assert from a verified Firebase ID token.

CREATE TABLE IF NOT EXISTS public.admins (
    firebase_uid  text PRIMARY KEY,
    email         text NOT NULL UNIQUE,
    display_name  text,
    role          text NOT NULL DEFAULT 'admin'
                  CHECK (role IN ('admin', 'superadmin')),
    is_active     boolean NOT NULL DEFAULT true,
    created_at    timestamptz NOT NULL DEFAULT now(),
    last_login_at timestamptz
);

COMMENT ON TABLE public.admins IS
    'Admin console operators. firebase_uid matches Firebase Auth; email is '
    'what is_admin() matches against the JWT claim.';

CREATE INDEX IF NOT EXISTS admins_email_active_idx
    ON public.admins (email) WHERE is_active;


-- =====================================================================
-- 2. PAYMENT REVIEW STATE
-- =====================================================================
-- Today payment_receipts has no id, no timestamps and no review state:
-- approving is a bare `UPDATE users SET subscription_status='active'` with
-- no record of who did it, when, or why a rejection happened.
--
-- payment_repository.dart inserts exactly five columns (user_id,
-- receipt_path, receipt_url, payment_method, verification_url) and supplies
-- no id or timestamp, so everything added here must be defaulted or
-- nullable or the student app's insert breaks.

-- id: add as a plain bigserial-equivalent only if no PK exists yet.
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name   = 'payment_receipts'
          AND column_name  = 'id'
    ) THEN
        ALTER TABLE public.payment_receipts
            ADD COLUMN id bigint GENERATED BY DEFAULT AS IDENTITY;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE table_schema   = 'public'
          AND table_name     = 'payment_receipts'
          AND constraint_type = 'PRIMARY KEY'
    ) THEN
        ALTER TABLE public.payment_receipts
            ADD CONSTRAINT payment_receipts_pkey PRIMARY KEY (id);
    END IF;
END $$;

ALTER TABLE public.payment_receipts
    ADD COLUMN IF NOT EXISTS created_at       timestamptz DEFAULT now(),
    ADD COLUMN IF NOT EXISTS status           text NOT NULL DEFAULT 'pending',
    ADD COLUMN IF NOT EXISTS amount           numeric(10, 2),
    ADD COLUMN IF NOT EXISTS currency         text DEFAULT 'ETB',
    ADD COLUMN IF NOT EXISTS reviewed_by      text,
    ADD COLUMN IF NOT EXISTS reviewed_at      timestamptz,
    ADD COLUMN IF NOT EXISTS rejection_reason text;

-- Constraints added separately so re-running cannot fail on a duplicate.
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'payment_receipts_status_check'
    ) THEN
        ALTER TABLE public.payment_receipts
            ADD CONSTRAINT payment_receipts_status_check
            CHECK (status IN ('pending', 'approved', 'rejected'));
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'payment_receipts_reviewed_by_fkey'
    ) THEN
        ALTER TABLE public.payment_receipts
            ADD CONSTRAINT payment_receipts_reviewed_by_fkey
            FOREIGN KEY (reviewed_by) REFERENCES public.admins (firebase_uid);
    END IF;
END $$;

-- Backfill rows that predate this migration. Every historical receipt is
-- treated as unreviewed, which is truthful: no review state was recorded.
-- The price is the hardcoded 250 ETB string from premium.dart:56 — it was
-- never stored, so this is a reconstruction, not a measurement.
UPDATE public.payment_receipts
   SET status = 'pending'
 WHERE status IS NULL;

UPDATE public.payment_receipts
   SET amount = 250
 WHERE amount IS NULL;

UPDATE public.payment_receipts
   SET currency = 'ETB'
 WHERE currency IS NULL;

UPDATE public.payment_receipts
   SET created_at = now()
 WHERE created_at IS NULL;

CREATE INDEX IF NOT EXISTS payment_receipts_status_created_idx
    ON public.payment_receipts (status, created_at DESC);

CREATE INDEX IF NOT EXISTS payment_receipts_user_idx
    ON public.payment_receipts (user_id);

COMMENT ON COLUMN public.payment_receipts.amount IS
    'Reconstructed for pre-existing rows: the 250 ETB price was hardcoded in '
    'the client (premium.dart:56) and never transmitted or validated.';


-- =====================================================================
-- 3. IMMUTABLE AUDIT LOG
-- =====================================================================
-- Append-only by policy (§8) and by the absence of any UPDATE/DELETE grant.
-- admin_uid is intentionally NOT a foreign key: an audit row must survive
-- the deletion of the admin who wrote it.

CREATE TABLE IF NOT EXISTS public.admin_audit_log (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_uid   text NOT NULL,
    action      text NOT NULL,
    entity_type text NOT NULL,
    entity_id   text,
    before      jsonb,
    after       jsonb,
    note        text,
    created_at  timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.admin_audit_log IS
    'Append-only. action: approve_payment | reject_payment | broadcast | '
    'edit_user | create_test | delete_question | ... '
    'entity_type: payment_receipt | user | test | question | ...';

CREATE INDEX IF NOT EXISTS admin_audit_log_created_idx
    ON public.admin_audit_log (created_at DESC);

CREATE INDEX IF NOT EXISTS admin_audit_log_admin_created_idx
    ON public.admin_audit_log (admin_uid, created_at DESC);

CREATE INDEX IF NOT EXISTS admin_audit_log_entity_idx
    ON public.admin_audit_log (entity_type, entity_id);


-- =====================================================================
-- 4. TEST ATTEMPTS  — closes the analytics gap
-- =====================================================================
-- `results` and `bookmarks` live ONLY in per-device SQLite and are never
-- uploaded, so "tests taken", "average score" and per-subject performance
-- are not computable app-wide today. This table is where the student app
-- (Phase 12 item 1) will sync completed attempts.
--
-- Three deliberate differences from the local SQLite `results` table:
--   * attempted_at    — a real attempt timestamp. The local table has none,
--                       so AnalyticsController currently filters by
--                       tests.created_at, i.e. when the test was AUTHORED.
--   * question_count  — explicit, so a score never requires decoding a JSON
--                       answers blob.
--   * no UNIQUE(user_id, test_id) — the local table keeps only the latest
--                       attempt; here history accumulates.

CREATE TABLE IF NOT EXISTS public.test_attempts (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        text    NOT NULL,
    test_id        integer NOT NULL,
    subject_id     integer,
    test_type      text,
    grade          integer,
    correct_count  integer NOT NULL,
    question_count integer NOT NULL,
    score_pct      numeric(5, 2) GENERATED ALWAYS AS (
                       CASE WHEN question_count > 0
                            THEN round(correct_count::numeric * 100
                                       / question_count, 2)
                            ELSE 0
                       END
                   ) STORED,
    is_completed   boolean NOT NULL DEFAULT true,
    duration_secs  integer,
    attempted_at   timestamptz NOT NULL DEFAULT now(),
    synced_at      timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.test_attempts IS
    'Server-side attempt history. Until the student app syncs to it '
    '(Phase 12 item 1) this table is empty and every learning metric on the '
    'admin dashboard must render an explicit empty state, never a zero.';

CREATE INDEX IF NOT EXISTS test_attempts_attempted_idx
    ON public.test_attempts (attempted_at DESC);

CREATE INDEX IF NOT EXISTS test_attempts_user_attempted_idx
    ON public.test_attempts (user_id, attempted_at DESC);

CREATE INDEX IF NOT EXISTS test_attempts_subject_idx
    ON public.test_attempts (subject_id);

CREATE INDEX IF NOT EXISTS test_attempts_type_idx
    ON public.test_attempts (test_type);


-- =====================================================================
-- 5. PER-USER READ STATE FOR BROADCASTS
-- =====================================================================
-- notifications.is_read is a single scalar on a shared user_id IS NULL row,
-- so the first student to tap a broadcast marks it read for EVERYONE. And
-- markAllRead's `.eq('user_id', userId)` never matches broadcast rows, so it
-- silently reverts on the next sync.
--
-- user_id is text, matching users.id (a Firebase UID). It is NOT a foreign
-- key to users because the student app writes this row and a strict FK adds
-- a failure mode for no benefit.

CREATE TABLE IF NOT EXISTS public.notification_reads (
    notification_id bigint NOT NULL
                    REFERENCES public.notifications (id) ON DELETE CASCADE,
    user_id         text NOT NULL,
    read_at         timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (notification_id, user_id)
);

CREATE INDEX IF NOT EXISTS notification_reads_user_idx
    ON public.notification_reads (user_id);


-- =====================================================================
-- 6. ACTIVITY AND SIGNUP METRICS
-- =====================================================================
-- users.created_at is never read or written by the client, so its existence
-- was unverified. Adding it with a default makes signup-over-time
-- computable. NOTE: pre-existing rows get now() as their created_at, which
-- means the signup chart shows a spike on the migration date for the entire
-- back catalogue. That is a known artefact — do not read it as real growth.

ALTER TABLE public.users
    ADD COLUMN IF NOT EXISTS created_at     timestamptz DEFAULT now(),
    ADD COLUMN IF NOT EXISTS last_active_at timestamptz;

COMMENT ON COLUMN public.users.created_at IS
    'Backfilled to the migration timestamp for rows that predate it. Signup '
    'analytics before that date are not meaningful.';

-- Attribute broadcasts to the admin who sent them.
ALTER TABLE public.notifications
    ADD COLUMN IF NOT EXISTS created_by text;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'notifications_created_by_fkey'
    ) THEN
        ALTER TABLE public.notifications
            ADD CONSTRAINT notifications_created_by_fkey
            FOREIGN KEY (created_by) REFERENCES public.admins (firebase_uid);
    END IF;
END $$;


-- =====================================================================
-- 7. AGGREGATE RPCs
-- =====================================================================
-- SECURITY DEFINER so the dashboard makes one round trip instead of ten,
-- and so it can read tables the caller has no direct select on. Each is
-- revoked from anon and granted only to authenticated, and each re-checks
-- is_admin() internally — SECURITY DEFINER without that check would be a
-- privilege escalation for any signed-in anonymous student client.
--
-- search_path is pinned on every definer function to prevent search-path
-- hijacking.

-- is_admin() is defined before the RPCs that call it.
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
    SELECT EXISTS (
        SELECT 1
        FROM public.admins a
        WHERE a.is_active
          AND lower(a.email) = lower(coalesce(auth.jwt() ->> 'email', ''))
    );
$$;

COMMENT ON FUNCTION public.is_admin() IS
    'True when the caller''s JWT email claim matches an active admins row. '
    'Matches on email rather than uid because that is the claim the '
    'admin-auth edge function can assert from a verified Firebase token.';


CREATE OR REPLACE FUNCTION public.admin_kpis()
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    result jsonb;
BEGIN
    IF NOT public.is_admin() THEN
        RAISE EXCEPTION 'not authorised';
    END IF;

    SELECT jsonb_build_object(
        'total_users',        (SELECT count(*) FROM public.users),
        'active_users',       (SELECT count(*) FROM public.users
                               WHERE subscription_status = 'active'),
        'pending_users',      (SELECT count(*) FROM public.users
                               WHERE subscription_status = 'pending'),
        'inactive_users',     (SELECT count(*) FROM public.users
                               WHERE subscription_status = 'inactive'),
        'stream_natural',     (SELECT count(*) FROM public.users
                               WHERE stream = 'natural'),
        'stream_social',      (SELECT count(*) FROM public.users
                               WHERE stream = 'social'),
        'stream_common',      (SELECT count(*) FROM public.users
                               WHERE stream = 'common'),
        'pending_payments',   (SELECT count(*) FROM public.payment_receipts
                               WHERE status = 'pending'),
        'approved_revenue',   (SELECT coalesce(sum(amount), 0)
                               FROM public.payment_receipts
                               WHERE status = 'approved'),
        'attempts_today',     (SELECT count(*) FROM public.test_attempts
                               WHERE attempted_at >= date_trunc('day', now())),
        'attempts_7d',        (SELECT count(*) FROM public.test_attempts
                               WHERE attempted_at >= now() - interval '7 days'),
        'attempts_30d',       (SELECT count(*) FROM public.test_attempts
                               WHERE attempted_at >= now() - interval '30 days'),
        'push_reachable',     (SELECT count(*) FROM public.users
                               WHERE fcm_token IS NOT NULL
                                 AND fcm_token <> ''),
        -- Honesty metric for the dashboard banner: what share of users have
        -- ever synced an attempt. Until Phase 12 ships this is 0.
        'users_with_attempts',(SELECT count(DISTINCT user_id)
                               FROM public.test_attempts)
    ) INTO result;

    RETURN result;
END;
$$;


CREATE OR REPLACE FUNCTION public.admin_signups_daily(days integer DEFAULT 30)
RETURNS TABLE (day date, count integer)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
    IF NOT public.is_admin() THEN
        RAISE EXCEPTION 'not authorised';
    END IF;

    RETURN QUERY
    SELECT d.day::date,
           coalesce(count(u.id), 0)::integer
    FROM generate_series(
             date_trunc('day', now()) - make_interval(days => days - 1),
             date_trunc('day', now()),
             interval '1 day'
         ) AS d(day)
    LEFT JOIN public.users u
           ON date_trunc('day', u.created_at) = d.day
    GROUP BY d.day
    ORDER BY d.day;
END;
$$;


CREATE OR REPLACE FUNCTION public.admin_revenue_daily(days integer DEFAULT 30)
RETURNS TABLE (day date, amount numeric, count integer)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
    IF NOT public.is_admin() THEN
        RAISE EXCEPTION 'not authorised';
    END IF;

    RETURN QUERY
    SELECT d.day::date,
           coalesce(sum(p.amount), 0)::numeric,
           count(p.id)::integer
    FROM generate_series(
             date_trunc('day', now()) - make_interval(days => days - 1),
             date_trunc('day', now()),
             interval '1 day'
         ) AS d(day)
    LEFT JOIN public.payment_receipts p
           ON date_trunc('day', p.reviewed_at) = d.day
          AND p.status = 'approved'
    GROUP BY d.day
    ORDER BY d.day;
END;
$$;


CREATE OR REPLACE FUNCTION public.admin_attempts_daily(days integer DEFAULT 30)
RETURNS TABLE (day date, attempts integer, avg_score numeric)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
    IF NOT public.is_admin() THEN
        RAISE EXCEPTION 'not authorised';
    END IF;

    RETURN QUERY
    SELECT d.day::date,
           count(a.id)::integer,
           round(coalesce(avg(a.score_pct), 0), 2)
    FROM generate_series(
             date_trunc('day', now()) - make_interval(days => days - 1),
             date_trunc('day', now()),
             interval '1 day'
         ) AS d(day)
    LEFT JOIN public.test_attempts a
           ON date_trunc('day', a.attempted_at) = d.day
    GROUP BY d.day
    ORDER BY d.day;
END;
$$;


CREATE OR REPLACE FUNCTION public.admin_subject_performance()
RETURNS TABLE (
    subject_id   integer,
    subject_name text,
    attempts     integer,
    avg_score    numeric
)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
    IF NOT public.is_admin() THEN
        RAISE EXCEPTION 'not authorised';
    END IF;

    RETURN QUERY
    SELECT s.id,
           s.name,
           count(a.id)::integer,
           round(coalesce(avg(a.score_pct), 0), 2)
    FROM public.subjects s
    LEFT JOIN public.test_attempts a ON a.subject_id = s.id
    GROUP BY s.id, s.name
    ORDER BY round(coalesce(avg(a.score_pct), 0), 2) ASC;  -- worst first
END;
$$;


CREATE OR REPLACE FUNCTION public.admin_test_type_distribution()
RETURNS TABLE (test_type text, attempts integer)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
    IF NOT public.is_admin() THEN
        RAISE EXCEPTION 'not authorised';
    END IF;

    RETURN QUERY
    SELECT coalesce(a.test_type, 'unknown'),
           count(*)::integer
    FROM public.test_attempts a
    GROUP BY coalesce(a.test_type, 'unknown')
    ORDER BY count(*) DESC;
END;
$$;


CREATE OR REPLACE FUNCTION public.admin_funnel()
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    result jsonb;
BEGIN
    IF NOT public.is_admin() THEN
        RAISE EXCEPTION 'not authorised';
    END IF;

    SELECT jsonb_build_object(
        'signups',           (SELECT count(*) FROM public.users),
        'first_attempt',     (SELECT count(DISTINCT user_id)
                              FROM public.test_attempts),
        'payment_submitted', (SELECT count(DISTINCT user_id)
                              FROM public.payment_receipts),
        'approved',          (SELECT count(DISTINCT user_id)
                              FROM public.payment_receipts
                              WHERE status = 'approved')
    ) INTO result;

    RETURN result;
END;
$$;


-- Lock the RPCs down: anon (the key inside the student APK) gets nothing.
DO $$
DECLARE
    fn text;
BEGIN
    FOREACH fn IN ARRAY ARRAY[
        'public.admin_kpis()',
        'public.admin_signups_daily(integer)',
        'public.admin_revenue_daily(integer)',
        'public.admin_attempts_daily(integer)',
        'public.admin_subject_performance()',
        'public.admin_test_type_distribution()',
        'public.admin_funnel()',
        'public.is_admin()'
    ]
    LOOP
        EXECUTE format('REVOKE ALL ON FUNCTION %s FROM PUBLIC', fn);
        EXECUTE format('REVOKE ALL ON FUNCTION %s FROM anon', fn);
        EXECUTE format('GRANT EXECUTE ON FUNCTION %s TO authenticated', fn);
    END LOOP;
END $$;


-- =====================================================================
-- 8. ROW LEVEL SECURITY
-- =====================================================================
-- RLS is enabled ONLY on the four tables this migration creates. Enabling
-- it on any pre-existing table would break the student app immediately,
-- because most of its repositories run as `anon` with no session at all.

ALTER TABLE public.admins             ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admin_audit_log    ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.test_attempts      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notification_reads ENABLE ROW LEVEL SECURITY;

-- ── admins ───────────────────────────────────────────────────────────
-- No anon access whatsoever. Admins may read the roster; only superadmins
-- may modify it, and §11 of the app layer additionally blocks self-demotion.
DROP POLICY IF EXISTS admins_select_admin ON public.admins;
CREATE POLICY admins_select_admin ON public.admins
    FOR SELECT TO authenticated
    USING (public.is_admin());

DROP POLICY IF EXISTS admins_write_superadmin ON public.admins;
CREATE POLICY admins_write_superadmin ON public.admins
    FOR ALL TO authenticated
    USING (
        EXISTS (
            SELECT 1 FROM public.admins a
            WHERE a.is_active
              AND a.role = 'superadmin'
              AND lower(a.email) = lower(coalesce(auth.jwt() ->> 'email', ''))
        )
    )
    WITH CHECK (
        EXISTS (
            SELECT 1 FROM public.admins a
            WHERE a.is_active
              AND a.role = 'superadmin'
              AND lower(a.email) = lower(coalesce(auth.jwt() ->> 'email', ''))
        )
    );

-- ── admin_audit_log ──────────────────────────────────────────────────
-- Readable and appendable by admins; NO update or delete policy exists, so
-- the table is immutable to every non-service role. That is the mechanism,
-- not merely a UI convention.
DROP POLICY IF EXISTS audit_select_admin ON public.admin_audit_log;
CREATE POLICY audit_select_admin ON public.admin_audit_log
    FOR SELECT TO authenticated
    USING (public.is_admin());

DROP POLICY IF EXISTS audit_insert_admin ON public.admin_audit_log;
CREATE POLICY audit_insert_admin ON public.admin_audit_log
    FOR INSERT TO authenticated
    WITH CHECK (public.is_admin());

-- ── test_attempts ────────────────────────────────────────────────────
-- The student client inserts its own attempts; only admins may read them.
-- Insert is open to anon because the student app has no real session (see
-- the header note) — it cannot prove ownership of user_id today. This is a
-- known weakness: a forged attempt row is possible. It is accepted because
-- attempts carry no entitlement, only analytics. Revisit if that changes.
DROP POLICY IF EXISTS attempts_insert_client ON public.test_attempts;
CREATE POLICY attempts_insert_client ON public.test_attempts
    FOR INSERT TO anon, authenticated
    WITH CHECK (true);

DROP POLICY IF EXISTS attempts_select_admin ON public.test_attempts;
CREATE POLICY attempts_select_admin ON public.test_attempts
    FOR SELECT TO authenticated
    USING (public.is_admin());

-- ── notification_reads ───────────────────────────────────────────────
-- Same reasoning: the student client must be able to record its own reads
-- while running as anon, and needs to read them back to compute unread.
DROP POLICY IF EXISTS reads_insert_client ON public.notification_reads;
CREATE POLICY reads_insert_client ON public.notification_reads
    FOR INSERT TO anon, authenticated
    WITH CHECK (true);

DROP POLICY IF EXISTS reads_select_client ON public.notification_reads;
CREATE POLICY reads_select_client ON public.notification_reads
    FOR SELECT TO anon, authenticated
    USING (true);


-- =====================================================================
-- ⚠️  POLICIES YOU MUST STILL REVIEW BY HAND
-- =====================================================================
-- This migration deliberately does NOT touch RLS on the pre-existing
-- tables, because doing so blindly would take the student app down. Review
-- each of these in the dashboard and decide:
--
--   public.users
--     If anon has UPDATE, a student can run
--       UPDATE users SET subscription_status='active' WHERE id='<own uid>'
--     with the anon key that ships inside the APK — self-granting premium
--     and making this entire approval workflow theatre. THIS IS THE SINGLE
--     MOST IMPORTANT THING TO CHECK.
--     Constraint on any fix: user_repository.dart upserts and updates the
--     row as anon, and auth.uid() is an unrelated anonymous uuid, so
--     "only your own row" is not expressible today. Closing this properly
--     needs the student app to hold a real session (a student equivalent of
--     the admin-auth exchange), or the writes to move behind an edge
--     function. Until then, narrowing anon UPDATE to a column allowlist
--     that EXCLUDES subscription_status is the pragmatic mitigation.
--
--   public.payment_receipts
--     Anon insert is required (students submit receipts). Anon UPDATE must
--     be denied, or a student could self-approve by writing
--     status='approved'. Note payment_repository.dart:89 does
--     .delete().eq('user_id', ...).select(), so a DELETE policy AND a
--     SELECT policy are both needed or that call silently returns [].
--
--   public.user_sessions
--     Anon write is required by session_service.dart, but unrestricted
--     write lets a user reset their own device lock and top up `trial`
--     freely — which makes the single-device lock advisory at best.
--     (It is soft regardless: device_id is a SharedPreferences uuid that
--     resets on reinstall.)
--
--   public.subjects / chapters / tests / questions / passages
--     Must remain anon-readable — the sync path has no session. Anon must
--     NOT have write access. Also note realtime_service.dart subscribes to
--     unfiltered `questions` UPDATEs, so every client receives every
--     question update; RLS on questions is what bounds that.
--
-- Realtime prerequisites already documented in realtime_service.dart:13-15
-- and required for users, questions and user_sessions alike:
--     ALTER PUBLICATION supabase_realtime ADD TABLE public.users;
--     ALTER TABLE public.users REPLICA IDENTITY FULL;
-- REPLICA IDENTITY FULL matters because the callbacks build whole models
-- from payload.newRecord; under the default identity unchanged columns are
-- omitted and those constructions throw.
-- =====================================================================

COMMIT;


-- =====================================================================
-- ROLLBACK
-- =====================================================================
-- Reverses everything above. The DROP COLUMN statements destroy review
-- state and are NOT safe once the admin app has been used in anger —
-- approvals, amounts and rejection reasons are only stored here.
--
-- BEGIN;
--
-- DROP FUNCTION IF EXISTS public.admin_funnel();
-- DROP FUNCTION IF EXISTS public.admin_test_type_distribution();
-- DROP FUNCTION IF EXISTS public.admin_subject_performance();
-- DROP FUNCTION IF EXISTS public.admin_attempts_daily(integer);
-- DROP FUNCTION IF EXISTS public.admin_revenue_daily(integer);
-- DROP FUNCTION IF EXISTS public.admin_signups_daily(integer);
-- DROP FUNCTION IF EXISTS public.admin_kpis();
--
-- DROP TABLE IF EXISTS public.notification_reads;
-- DROP TABLE IF EXISTS public.test_attempts;
-- DROP TABLE IF EXISTS public.admin_audit_log;
--
-- ALTER TABLE public.notifications
--     DROP CONSTRAINT IF EXISTS notifications_created_by_fkey,
--     DROP COLUMN IF EXISTS created_by;
--
-- ALTER TABLE public.users
--     DROP COLUMN IF EXISTS last_active_at,
--     DROP COLUMN IF EXISTS created_at;
--
-- ALTER TABLE public.payment_receipts
--     DROP CONSTRAINT IF EXISTS payment_receipts_reviewed_by_fkey,
--     DROP CONSTRAINT IF EXISTS payment_receipts_status_check,
--     DROP COLUMN IF EXISTS rejection_reason,
--     DROP COLUMN IF EXISTS reviewed_at,
--     DROP COLUMN IF EXISTS reviewed_by,
--     DROP COLUMN IF EXISTS currency,
--     DROP COLUMN IF EXISTS amount,
--     DROP COLUMN IF EXISTS status,
--     DROP COLUMN IF EXISTS created_at;
--
-- DROP FUNCTION IF EXISTS public.is_admin();
-- DROP TABLE IF EXISTS public.admins;
--
-- COMMIT;
