-- =====================================================================
-- MatricMate Complete Database Schema (Master Fresh Install)
-- Native Supabase Auth with Strict Row-Level Security (RLS)
-- =====================================================================

BEGIN;

-- ─────────────────────────────────────────────────────────────────────
-- 1. EXTENSIONS
-- ─────────────────────────────────────────────────────────────────────
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ─────────────────────────────────────────────────────────────────────
-- 2. CORE IDENTITY & USER TABLES
-- ─────────────────────────────────────────────────────────────────────

-- public.users (Primary Profile Table, 1:1 linked with auth.users)
CREATE TABLE IF NOT EXISTS public.users (
    id                  uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    first_name          text NOT NULL DEFAULT '',
    last_name           text DEFAULT '',
    email               text NOT NULL,
    stream              text DEFAULT 'natural',
    subscription_status text NOT NULL DEFAULT 'inactive',
    fcm_token           text,
    created_at          timestamptz NOT NULL DEFAULT now(),
    last_active_at      timestamptz
);

CREATE INDEX IF NOT EXISTS users_subscription_idx ON public.users (subscription_status);
CREATE INDEX IF NOT EXISTS users_stream_idx       ON public.users (stream);

-- public.user_sessions (Single-device session enforcement)
CREATE TABLE IF NOT EXISTS public.user_sessions (
    user_id    uuid PRIMARY KEY REFERENCES public.users(id) ON DELETE CASCADE,
    device_id  text NOT NULL,
    trial      integer NOT NULL DEFAULT 5,
    updated_at timestamptz NOT NULL DEFAULT now()
);

-- public.admins (Admin Role Table)
CREATE TABLE IF NOT EXISTS public.admins (
    id            uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    email         text NOT NULL UNIQUE,
    display_name  text,
    role          text NOT NULL DEFAULT 'admin' CHECK (role IN ('admin', 'superadmin')),
    is_active     boolean NOT NULL DEFAULT true,
    created_at    timestamptz NOT NULL DEFAULT now(),
    last_login_at timestamptz
);

CREATE INDEX IF NOT EXISTS admins_email_active_idx ON public.admins (email) WHERE is_active;

-- public.admin_audit_log (Immutable administrative actions log)
CREATE TABLE IF NOT EXISTS public.admin_audit_log (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_uid   text NOT NULL,
    action      text NOT NULL,
    entity_type text NOT NULL,
    entity_id   text,
    before      jsonb,
    after       jsonb,
    note        text,
    created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS admin_audit_log_created_idx       ON public.admin_audit_log (created_at DESC);
CREATE INDEX IF NOT EXISTS admin_audit_log_admin_created_idx ON public.admin_audit_log (admin_uid, created_at DESC);
CREATE INDEX IF NOT EXISTS admin_audit_log_entity_idx        ON public.admin_audit_log (entity_type, entity_id);

-- ─────────────────────────────────────────────────────────────────────
-- 3. CONTENT TABLES (Subjects, Chapters, Passages, Tests, Questions)
-- ─────────────────────────────────────────────────────────────────────

-- public.subjects
CREATE TABLE IF NOT EXISTS public.subjects (
    id                     integer PRIMARY KEY,
    name                   text    NOT NULL UNIQUE,
    is_natural             boolean NOT NULL DEFAULT false,
    is_common              boolean NOT NULL DEFAULT false,
    is_downloaded          boolean NOT NULL DEFAULT false,
    is_entrance_downloaded boolean NOT NULL DEFAULT false,
    entrance_count         integer NOT NULL DEFAULT 0,
    model_count            integer NOT NULL DEFAULT 0
);

-- public.chapters
CREATE TABLE IF NOT EXISTS public.chapters (
    id             integer PRIMARY KEY,
    subject_id     integer NOT NULL REFERENCES public.subjects(id) ON DELETE CASCADE,
    grade          integer NOT NULL,
    chapter_number integer NOT NULL,
    title          text    NOT NULL
);

CREATE INDEX IF NOT EXISTS chapters_subject_idx ON public.chapters (subject_id);

-- public.passages
CREATE TABLE IF NOT EXISTS public.passages (
    id         integer PRIMARY KEY,
    content    text    NOT NULL,
    title      text,
    image_url  text,
    updated_at timestamptz
);

-- public.question_sections
CREATE TABLE IF NOT EXISTS public.question_sections (
    id    integer PRIMARY KEY,
    title text NOT NULL
);

-- public.tests
CREATE TABLE IF NOT EXISTS public.tests (
    id             integer PRIMARY KEY,
    subject_id     integer NOT NULL REFERENCES public.subjects(id) ON DELETE CASCADE,
    chapter_id     integer REFERENCES public.chapters(id) ON DELETE CASCADE,
    grade          integer,
    title          text    NOT NULL,
    type           text    NOT NULL DEFAULT 'chapter',
    question_count integer NOT NULL,
    time           integer NOT NULL DEFAULT -1,
    description    text,
    created_at     timestamptz NOT NULL DEFAULT now(),
    updated_at     timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS tests_subject_grade_chapter_idx ON public.tests (subject_id, grade, chapter_id);
CREATE INDEX IF NOT EXISTS tests_type_idx                  ON public.tests (type);

-- public.questions
CREATE TABLE IF NOT EXISTS public.questions (
    id                    integer PRIMARY KEY,
    test_id               integer NOT NULL REFERENCES public.tests(id) ON DELETE CASCADE,
    passage_id            integer REFERENCES public.passages(id) ON DELETE SET NULL,
    section_id            integer REFERENCES public.question_sections(id) ON DELETE SET NULL,
    question_number       integer NOT NULL,
    question_text         text    NOT NULL,
    question_image_url    text,
    choice_a              text    NOT NULL,
    choice_b              text    NOT NULL,
    choice_c              text    NOT NULL,
    choice_d              text    NOT NULL,
    correct_choice        text    NOT NULL,
    explanation           text,
    explanation_image_url text,
    has_diagram           boolean NOT NULL DEFAULT false,
    diagram_url           text,
    updated_at            timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS questions_test_idx    ON public.questions (test_id);
CREATE INDEX IF NOT EXISTS questions_passage_idx ON public.questions (passage_id);
CREATE INDEX IF NOT EXISTS questions_section_idx ON public.questions (section_id);

-- ─────────────────────────────────────────────────────────────────────
-- 4. STUDENT ACTIVITY (Bookmarks & Test Attempts)
-- ─────────────────────────────────────────────────────────────────────

-- public.bookmarks
CREATE TABLE IF NOT EXISTS public.bookmarks (
    user_id     uuid    NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    question_id integer NOT NULL REFERENCES public.questions(id) ON DELETE CASCADE,
    created_at  timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, question_id)
);

CREATE INDEX IF NOT EXISTS bookmarks_user_idx ON public.bookmarks (user_id);

-- public.test_attempts
CREATE TABLE IF NOT EXISTS public.test_attempts (
    id              serial PRIMARY KEY,
    user_id         uuid    NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    test_id         integer NOT NULL REFERENCES public.tests(id) ON DELETE CASCADE,
    score           integer NOT NULL,
    total_questions integer NOT NULL,
    completed_at    timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS test_attempts_user_idx ON public.test_attempts (user_id);
CREATE INDEX IF NOT EXISTS test_attempts_test_idx ON public.test_attempts (test_id);

-- ─────────────────────────────────────────────────────────────────────
-- 5. PAYMENT SUBSYSTEM
-- ─────────────────────────────────────────────────────────────────────

-- public.payment_requests
CREATE TABLE IF NOT EXISTS public.payment_requests (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         uuid        NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    plan_type       text        NOT NULL,
    amount          integer     NOT NULL,
    status          text        NOT NULL DEFAULT 'pending',
    transaction_ref text,
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS payment_requests_user_idx   ON public.payment_requests (user_id);
CREATE INDEX IF NOT EXISTS payment_requests_status_idx ON public.payment_requests (status);

-- public.payment_receipts
CREATE TABLE IF NOT EXISTS public.payment_receipts (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          uuid        NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    receipt_path     text        NOT NULL,
    status           text        NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
    amount           numeric     DEFAULT 250,
    currency         text        DEFAULT 'ETB',
    created_at       timestamptz NOT NULL DEFAULT now(),
    reviewed_at      timestamptz,
    reviewed_by      uuid        REFERENCES public.admins(id) ON DELETE SET NULL,
    rejection_reason text
);

CREATE INDEX IF NOT EXISTS payment_receipts_user_idx           ON public.payment_receipts (user_id);
CREATE INDEX IF NOT EXISTS payment_receipts_status_created_idx ON public.payment_receipts (status, created_at DESC);

-- ─────────────────────────────────────────────────────────────────────
-- 6. NOTIFICATIONS SUBSYSTEM
-- ─────────────────────────────────────────────────────────────────────

-- public.notifications
CREATE TABLE IF NOT EXISTS public.notifications (
    id         serial PRIMARY KEY,
    user_id    uuid REFERENCES public.users(id) ON DELETE CASCADE,
    title      text        NOT NULL,
    message    text        NOT NULL,
    type       text        NOT NULL DEFAULT 'general',
    data       jsonb,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS notifications_user_idx ON public.notifications (user_id);
CREATE INDEX IF NOT EXISTS notifications_type_idx ON public.notifications (type);

-- public.notification_reads
CREATE TABLE IF NOT EXISTS public.notification_reads (
    id              serial PRIMARY KEY,
    user_id         uuid    NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    notification_id integer NOT NULL REFERENCES public.notifications(id) ON DELETE CASCADE,
    read_at         timestamptz NOT NULL DEFAULT now(),
    UNIQUE (user_id, notification_id)
);

CREATE INDEX IF NOT EXISTS notification_reads_user_idx ON public.notification_reads (user_id);

-- ─────────────────────────────────────────────────────────────────────
-- 7. CHALLENGE SUBSYSTEM (Live Competitions & Leaderboards)
-- ─────────────────────────────────────────────────────────────────────

-- public.challenge_question_sets
CREATE TABLE IF NOT EXISTS public.challenge_question_sets (
    id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    title       text NOT NULL,
    description text,
    created_at  timestamptz NOT NULL DEFAULT now()
);

-- public.challenge_passages
CREATE TABLE IF NOT EXISTS public.challenge_passages (
    id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    title      text,
    content    text NOT NULL,
    image_url  text,
    created_at timestamptz NOT NULL DEFAULT now()
);

-- public.leaderboard_challenges
CREATE TABLE IF NOT EXISTS public.leaderboard_challenges (
    id               uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    title            text        NOT NULL,
    description      text,
    subject_id       integer     REFERENCES public.subjects(id) ON DELETE SET NULL,
    set_id           uuid        REFERENCES public.challenge_question_sets(id) ON DELETE SET NULL,
    start_time       timestamptz,
    end_time         timestamptz,
    starts_at        timestamptz,
    ends_at          timestamptz,
    duration_minutes integer     NOT NULL DEFAULT 15,
    duration_seconds integer     DEFAULT 900,
    status           text        NOT NULL DEFAULT 'draft',
    audience         text        DEFAULT 'both',
    xp_reward        integer     NOT NULL DEFAULT 100,
    coin_reward      integer     NOT NULL DEFAULT 50,
    badge_name       text,
    created_at       timestamptz NOT NULL DEFAULT now(),
    updated_at       timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS leaderboard_challenges_status_idx ON public.leaderboard_challenges (status);
CREATE INDEX IF NOT EXISTS leaderboard_challenges_window_idx ON public.leaderboard_challenges (start_time, end_time);

-- public.challenge_questions
CREATE TABLE IF NOT EXISTS public.challenge_questions (
    id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    challenge_id    uuid    REFERENCES public.leaderboard_challenges(id) ON DELETE CASCADE,
    set_id          uuid    REFERENCES public.challenge_question_sets(id) ON DELETE CASCADE,
    passage_id      uuid    REFERENCES public.challenge_passages(id) ON DELETE SET NULL,
    question_number integer,
    order_index     integer DEFAULT 0,
    question_text   text    NOT NULL,
    choices         jsonb,
    choice_a        text,
    choice_b        text,
    choice_c        text,
    choice_d        text,
    correct_choice  text    NOT NULL,
    explanation     text,
    explanation_en  text,
    explanation_am  text,
    image_url       text,
    points          integer NOT NULL DEFAULT 1,
    created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS challenge_questions_challenge_idx ON public.challenge_questions (challenge_id);
CREATE INDEX IF NOT EXISTS challenge_questions_set_idx       ON public.challenge_questions (set_id);

-- public.challenge_attempts
CREATE TABLE IF NOT EXISTS public.challenge_attempts (
    id                 uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    challenge_id       uuid    NOT NULL REFERENCES public.leaderboard_challenges(id) ON DELETE CASCADE,
    user_id            uuid    NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    stream             text    DEFAULT 'natural',
    started_at         timestamptz NOT NULL DEFAULT now(),
    completed_at       timestamptz,
    submitted_at       timestamptz,
    time_spent_seconds integer,
    total_time_seconds integer,
    score              integer DEFAULT 0,
    total_points       integer DEFAULT 0,
    status             text    NOT NULL DEFAULT 'in_progress',
    created_at         timestamptz NOT NULL DEFAULT now(),
    UNIQUE (challenge_id, user_id)
);

CREATE INDEX IF NOT EXISTS challenge_attempts_challenge_user_idx ON public.challenge_attempts (challenge_id, user_id);
CREATE INDEX IF NOT EXISTS challenge_attempts_leaderboard_idx    ON public.challenge_attempts (challenge_id, status, score DESC, total_time_seconds ASC);

-- public.challenge_answers
CREATE TABLE IF NOT EXISTS public.challenge_answers (
    id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    attempt_id      uuid    NOT NULL REFERENCES public.challenge_attempts(id) ON DELETE CASCADE,
    question_id     uuid    NOT NULL REFERENCES public.challenge_questions(id) ON DELETE CASCADE,
    selected_choice text,
    is_correct      boolean NOT NULL DEFAULT false,
    answered_at     timestamptz NOT NULL DEFAULT now(),
    UNIQUE (attempt_id, question_id)
);

CREATE INDEX IF NOT EXISTS challenge_answers_attempt_idx ON public.challenge_answers (attempt_id);

-- public.challenge_rewards
CREATE TABLE IF NOT EXISTS public.challenge_rewards (
    id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    challenge_id  uuid    NOT NULL REFERENCES public.leaderboard_challenges(id) ON DELETE CASCADE,
    user_id       uuid    NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    rank          integer NOT NULL,
    xp_earned     integer NOT NULL DEFAULT 0,
    coins_earned  integer NOT NULL DEFAULT 0,
    badge_awarded text,
    awarded_at    timestamptz NOT NULL DEFAULT now(),
    UNIQUE (challenge_id, user_id)
);

CREATE INDEX IF NOT EXISTS challenge_rewards_challenge_idx ON public.challenge_rewards (challenge_id);
CREATE INDEX IF NOT EXISTS challenge_rewards_user_idx      ON public.challenge_rewards (user_id);

-- ─────────────────────────────────────────────────────────────────────
-- 8. APPLICATION CONFIGURATION
-- ─────────────────────────────────────────────────────────────────────

-- public.app_config
CREATE TABLE IF NOT EXISTS public.app_config (
    key        text PRIMARY KEY,
    value      jsonb NOT NULL,
    updated_at timestamptz NOT NULL DEFAULT now()
);

-- ─────────────────────────────────────────────────────────────────────
-- 9. LEADERBOARD VIEWS
-- ─────────────────────────────────────────────────────────────────────

CREATE OR REPLACE VIEW public.v_challenge_leaderboard AS
SELECT
    ca.challenge_id,
    ca.user_id,
    coalesce(u.first_name, 'Student') AS first_name,
    coalesce(u.last_name, '') AS last_name,
    coalesce(ca.stream, u.stream, 'natural') AS stream,
    coalesce(ca.score, 0) AS score,
    coalesce(ca.score, 0) AS total_points,
    coalesce(ca.total_time_seconds, 0) AS total_time_seconds,
    ca.submitted_at,
    DENSE_RANK() OVER (
        PARTITION BY ca.challenge_id
        ORDER BY coalesce(ca.score, 0) DESC, coalesce(ca.total_time_seconds, 0) ASC, ca.submitted_at ASC
    ) AS rank
FROM public.challenge_attempts ca
LEFT JOIN public.users u ON u.id = ca.user_id
WHERE ca.status = 'submitted';

CREATE OR REPLACE VIEW public.v_challenge_leaderboard_weekly AS
SELECT
    ca.user_id,
    coalesce(u.first_name, 'Student') AS first_name,
    coalesce(u.last_name, '') AS last_name,
    coalesce(ca.stream, u.stream, 'natural') AS stream,
    sum(coalesce(ca.score, 0))::int AS total_score,
    count(ca.id)::int AS challenges_completed,
    DENSE_RANK() OVER (
        ORDER BY sum(coalesce(ca.score, 0)) DESC, sum(coalesce(ca.total_time_seconds, 0)) ASC
    ) AS rank
FROM public.challenge_attempts ca
LEFT JOIN public.users u ON u.id = ca.user_id
JOIN public.leaderboard_challenges lc ON lc.id = ca.challenge_id
WHERE ca.status = 'submitted'
  AND ca.submitted_at >= date_trunc('week', now())
GROUP BY ca.user_id, u.first_name, u.last_name, coalesce(ca.stream, u.stream, 'natural');

CREATE OR REPLACE VIEW public.v_challenge_leaderboard_monthly AS
SELECT
    ca.user_id,
    coalesce(u.first_name, 'Student') AS first_name,
    coalesce(u.last_name, '') AS last_name,
    coalesce(ca.stream, u.stream, 'natural') AS stream,
    sum(coalesce(ca.score, 0))::int AS total_score,
    count(ca.id)::int AS challenges_completed,
    DENSE_RANK() OVER (
        ORDER BY sum(coalesce(ca.score, 0)) DESC, sum(coalesce(ca.total_time_seconds, 0)) ASC
    ) AS rank
FROM public.challenge_attempts ca
LEFT JOIN public.users u ON u.id = ca.user_id
JOIN public.leaderboard_challenges lc ON lc.id = ca.challenge_id
WHERE ca.status = 'submitted'
  AND ca.submitted_at >= date_trunc('month', now())
GROUP BY ca.user_id, u.first_name, u.last_name, coalesce(ca.stream, u.stream, 'natural');

-- ─────────────────────────────────────────────────────────────────────
-- 10. FUNCTIONS, RPCS & TRIGGERS
-- ─────────────────────────────────────────────────────────────────────

-- Admin check helper
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
    SELECT EXISTS (
        SELECT 1
        FROM public.admins a
        WHERE a.is_active
          AND (
            a.id = auth.uid()
            OR lower(a.email) = lower(coalesce(auth.jwt() ->> 'email', ''))
          )
    );
$$;

-- Auto-provision user on auth signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
    INSERT INTO public.users (
        id,
        first_name,
        last_name,
        email,
        stream,
        subscription_status,
        created_at
    ) VALUES (
        NEW.id,
        COALESCE(NEW.raw_user_meta_data->>'first_name', ''),
        COALESCE(NEW.raw_user_meta_data->>'last_name', ''),
        COALESCE(NEW.email, ''),
        COALESCE(NEW.raw_user_meta_data->>'stream', 'natural'),
        'inactive',
        NOW()
    )
    ON CONFLICT (id) DO UPDATE SET
        email = EXCLUDED.email,
        first_name = CASE WHEN EXCLUDED.first_name <> '' THEN EXCLUDED.first_name ELSE public.users.first_name END,
        last_name = CASE WHEN EXCLUDED.last_name <> '' THEN EXCLUDED.last_name ELSE public.users.last_name END,
        stream = CASE WHEN EXCLUDED.stream <> '' THEN EXCLUDED.stream ELSE public.users.stream END;

    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- Self-service account deletion
CREATE OR REPLACE FUNCTION public.delete_own_account()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    v_uid uuid := auth.uid();
BEGIN
    IF v_uid IS NULL THEN
        RAISE EXCEPTION 'Not authenticated';
    END IF;

    DELETE FROM auth.users WHERE id = v_uid;
END;
$$;

GRANT EXECUTE ON FUNCTION public.delete_own_account() TO authenticated;

-- Admin approve payment RPC
CREATE OR REPLACE FUNCTION public.admin_approve_payment(
    p_receipt_id bigint,
    p_user_id    uuid,
    p_admin_uid  uuid,
    p_amount     numeric DEFAULT NULL,
    p_note       text    DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    v_receipt     public.payment_receipts%ROWTYPE;
    v_before      jsonb;
    v_after       jsonb;
    v_user_before text;
    v_reviewer    text;
BEGIN
    IF NOT public.is_admin() THEN
        RAISE EXCEPTION 'not authorised';
    END IF;

    SELECT * INTO v_receipt
    FROM public.payment_receipts
    WHERE id = p_receipt_id
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'receipt % not found', p_receipt_id;
    END IF;

    IF v_receipt.status <> 'pending' THEN
        SELECT coalesce(a.display_name, a.email, v_receipt.reviewed_by::text)
          INTO v_reviewer
          FROM public.admins a
         WHERE a.id = v_receipt.reviewed_by;

        RAISE EXCEPTION 'ALREADY_REVIEWED:%:%',
              v_receipt.status, coalesce(v_reviewer, 'another admin');
    END IF;

    v_before := to_jsonb(v_receipt);

    SELECT subscription_status INTO v_user_before
    FROM public.users WHERE id = p_user_id;

    UPDATE public.payment_receipts
       SET status      = 'approved',
           reviewed_by = p_admin_uid,
           reviewed_at = now(),
           amount      = coalesce(p_amount, amount, 250)
     WHERE id = p_receipt_id
     RETURNING * INTO v_receipt;

    v_after := to_jsonb(v_receipt);

    UPDATE public.users
       SET subscription_status = 'active'
     WHERE id = p_user_id;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'user % not found', p_user_id;
    END IF;

    INSERT INTO public.admin_audit_log
        (admin_uid, action, entity_type, entity_id, before, after, note)
    VALUES (
        p_admin_uid::text,
        'approve_payment',
        'payment_receipt',
        p_receipt_id::text,
        jsonb_build_object('receipt', v_before, 'user_subscription_status', v_user_before),
        jsonb_build_object('receipt', v_after, 'user_subscription_status', 'active'),
        p_note
    );

    RETURN jsonb_build_object(
        'ok', true,
        'receipt_id', p_receipt_id,
        'user_id', p_user_id,
        'amount', v_receipt.amount
    );
END;
$$;

-- Admin reject payment RPC
CREATE OR REPLACE FUNCTION public.admin_reject_payment(
    p_receipt_id bigint,
    p_user_id    uuid,
    p_admin_uid  uuid,
    p_reason     text
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    v_receipt     public.payment_receipts%ROWTYPE;
    v_before      jsonb;
    v_after       jsonb;
    v_user_before text;
    v_reviewer    text;
BEGIN
    IF NOT public.is_admin() THEN
        RAISE EXCEPTION 'not authorised';
    END IF;

    IF p_reason IS NULL OR btrim(p_reason) = '' THEN
        RAISE EXCEPTION 'a rejection reason is required';
    END IF;

    SELECT * INTO v_receipt
    FROM public.payment_receipts
    WHERE id = p_receipt_id
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'receipt % not found', p_receipt_id;
    END IF;

    IF v_receipt.status <> 'pending' THEN
        SELECT coalesce(a.display_name, a.email, v_receipt.reviewed_by::text)
          INTO v_reviewer
          FROM public.admins a
         WHERE a.id = v_receipt.reviewed_by;

        RAISE EXCEPTION 'ALREADY_REVIEWED:%:%',
              v_receipt.status, coalesce(v_reviewer, 'another admin');
    END IF;

    v_before := to_jsonb(v_receipt);

    SELECT subscription_status INTO v_user_before
    FROM public.users WHERE id = p_user_id;

    UPDATE public.payment_receipts
       SET status           = 'rejected',
           reviewed_by      = p_admin_uid,
           reviewed_at      = now(),
           rejection_reason = p_reason
     WHERE id = p_receipt_id
     RETURNING * INTO v_receipt;

    v_after := to_jsonb(v_receipt);

    UPDATE public.users
       SET subscription_status = 'inactive'
     WHERE id = p_user_id;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'user % not found', p_user_id;
    END IF;

    INSERT INTO public.admin_audit_log
        (admin_uid, action, entity_type, entity_id, before, after, note)
    VALUES (
        p_admin_uid::text,
        'reject_payment',
        'payment_receipt',
        p_receipt_id::text,
        jsonb_build_object('receipt', v_before, 'user_subscription_status', v_user_before),
        jsonb_build_object('receipt', v_after, 'user_subscription_status', 'inactive'),
        p_reason
    );

    RETURN jsonb_build_object('ok', true, 'receipt_id', p_receipt_id, 'user_id', p_user_id);
END;
$$;

-- Admin set subscription status override
CREATE OR REPLACE FUNCTION public.admin_set_subscription_status(
    p_user_id   uuid,
    p_status    text,
    p_admin_uid uuid,
    p_note      text DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    v_before text;
BEGIN
    IF NOT public.is_admin() THEN
        RAISE EXCEPTION 'not authorised';
    END IF;

    IF p_status NOT IN ('active', 'pending', 'inactive') THEN
        RAISE EXCEPTION 'status must be active, pending or inactive (got %)', p_status;
    END IF;

    SELECT subscription_status INTO v_before
    FROM public.users WHERE id = p_user_id FOR UPDATE;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'user % not found', p_user_id;
    END IF;

    UPDATE public.users
       SET subscription_status = p_status
     WHERE id = p_user_id;

    INSERT INTO public.admin_audit_log
        (admin_uid, action, entity_type, entity_id, before, after, note)
    VALUES (
        p_admin_uid::text,
        'set_subscription_status',
        'user',
        p_user_id::text,
        jsonb_build_object('subscription_status', v_before),
        jsonb_build_object('subscription_status', p_status),
        p_note
    );

    RETURN jsonb_build_object('ok', true, 'before', v_before, 'after', p_status);
END;
$$;

-- Challenge RPC: Start Attempt (Anti-Cheating, questions without correct_choice)
CREATE OR REPLACE FUNCTION public.rpc_start_attempt(
  p_challenge_id uuid,
  p_user_id text
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_challenge record;
  v_user record;
  v_attempt record;
  v_questions jsonb;
  v_target_uid uuid;
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'not_authenticated';
  END IF;

  v_target_uid := p_user_id::uuid;
  IF auth.uid() != v_target_uid AND NOT public.is_admin() THEN
    RAISE EXCEPTION 'unauthorized';
  END IF;

  SELECT * INTO v_challenge FROM public.leaderboard_challenges WHERE id = p_challenge_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'challenge_not_found';
  END IF;

  IF v_challenge.status NOT IN ('live', 'scheduled') THEN
    RAISE EXCEPTION 'challenge_not_active';
  END IF;

  -- If challenge is live but starts_at is in the future (e.g. forced live from scheduled),
  -- heal starts_at so that students can attempt immediately.
  IF v_challenge.status = 'live' AND v_challenge.starts_at IS NOT NULL AND now() < v_challenge.starts_at THEN
    UPDATE public.leaderboard_challenges
    SET starts_at = now() - interval '10 seconds'
    WHERE id = v_challenge.id;
    v_challenge.starts_at := now() - interval '10 seconds';
  END IF;

  -- Only scheduled challenges block attempts with 'challenge_not_started'
  IF v_challenge.status = 'scheduled' AND v_challenge.starts_at IS NOT NULL AND now() < v_challenge.starts_at THEN
    RAISE EXCEPTION 'challenge_not_started';
  END IF;

  IF v_challenge.ends_at IS NOT NULL AND now() > v_challenge.ends_at THEN
    RAISE EXCEPTION 'challenge_ended';
  END IF;

  SELECT * INTO v_user FROM public.users WHERE id = v_target_uid;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'user_not_found';
  END IF;

  IF v_challenge.audience != 'both' AND lower(v_challenge.audience) != lower(coalesce(v_user.stream, '')) THEN
    RAISE EXCEPTION 'stream_not_eligible';
  END IF;

  INSERT INTO public.challenge_attempts (
    challenge_id, user_id, stream, started_at, status
  )
  VALUES (
    v_challenge.id, v_user.id, coalesce(v_user.stream, 'natural'), now(), 'in_progress'
  )
  ON CONFLICT (challenge_id, user_id)
  DO UPDATE SET started_at = challenge_attempts.started_at
  RETURNING * INTO v_attempt;

  IF v_attempt.status = 'submitted' THEN
    RAISE EXCEPTION 'already_submitted';
  END IF;

  SELECT jsonb_agg(
    jsonb_build_object(
      'id', q.id,
      'order_index', q.order_index,
      'question_text', q.question_text,
      'choices', q.choices,
      'image_url', q.image_url,
      'passage_id', q.passage_id,
      'passage', CASE WHEN cp.id IS NOT NULL THEN jsonb_build_object(
        'id', -1,
        'title', cp.title,
        'content', cp.content,
        'image_url', cp.image_url
      ) ELSE NULL END
    ) ORDER BY q.order_index ASC
  ) INTO v_questions
  FROM public.challenge_questions q
  LEFT JOIN public.challenge_passages cp ON cp.id = q.passage_id
  WHERE (q.challenge_id = v_challenge.id
     OR (v_challenge.set_id IS NOT NULL AND q.set_id = v_challenge.set_id)
     OR q.set_id = v_challenge.id);

  RETURN jsonb_build_object(
    'attempt_id', v_attempt.id,
    'challenge_id', v_challenge.id,
    'title', v_challenge.title,
    'duration_seconds', v_challenge.duration_seconds,
    'started_at', v_attempt.started_at,
    'ends_at', v_challenge.ends_at,
    'questions', coalesce(v_questions, '[]'::jsonb)
  );
END;
$$;

-- Challenge RPC: Start Challenge Attempt (Alias wrapper)
CREATE OR REPLACE FUNCTION public.rpc_start_challenge_attempt(
  p_challenge_id uuid,
  p_user_id text
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  RETURN public.rpc_start_attempt(p_challenge_id, p_user_id);
END;
$$;

-- Challenge RPC: Submit Answer
CREATE OR REPLACE FUNCTION public.rpc_submit_answer(
  p_attempt_id uuid,
  p_question_id uuid,
  p_selected_choice text
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_attempt record;
  v_question record;
  v_is_correct boolean := false;
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'not_authenticated';
  END IF;

  SELECT * INTO v_attempt FROM public.challenge_attempts WHERE id = p_attempt_id;
  IF NOT FOUND OR v_attempt.status != 'in_progress' THEN
    RAISE EXCEPTION 'invalid_or_completed_attempt';
  END IF;

  IF auth.uid() != v_attempt.user_id AND NOT public.is_admin() THEN
    RAISE EXCEPTION 'unauthorized';
  END IF;

  SELECT * INTO v_question FROM public.challenge_questions WHERE id = p_question_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'question_not_found';
  END IF;

  IF trim(lower(coalesce(v_question.correct_choice, ''))) = trim(lower(coalesce(p_selected_choice, ''))) THEN
    v_is_correct := true;
  END IF;

  INSERT INTO public.challenge_answers (attempt_id, question_id, selected_choice, is_correct, answered_at)
  VALUES (p_attempt_id, p_question_id, p_selected_choice, v_is_correct, now())
  ON CONFLICT (attempt_id, question_id)
  DO UPDATE SET
    selected_choice = EXCLUDED.selected_choice,
    is_correct = EXCLUDED.is_correct,
    answered_at = EXCLUDED.answered_at;

  RETURN jsonb_build_object('success', true);
END;
$$;

-- Challenge RPC: Submit Attempt
CREATE OR REPLACE FUNCTION public.rpc_submit_attempt(
  p_attempt_id uuid,
  p_total_time_seconds int DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_attempt record;
  v_challenge record;
  v_score int := 0;
  v_time int := 0;
  v_questions jsonb;
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'not_authenticated';
  END IF;

  SELECT * INTO v_attempt FROM public.challenge_attempts WHERE id = p_attempt_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'attempt_not_found';
  END IF;

  IF auth.uid() != v_attempt.user_id AND NOT public.is_admin() THEN
    RAISE EXCEPTION 'unauthorized';
  END IF;

  IF v_attempt.status = 'submitted' THEN
    RETURN jsonb_build_object(
      'success', true,
      'score', v_attempt.score,
      'total_time_seconds', v_attempt.total_time_seconds,
      'status', v_attempt.status
    );
  END IF;

  SELECT * INTO v_challenge FROM public.leaderboard_challenges WHERE id = v_attempt.challenge_id;

  SELECT count(*)::int INTO v_score
  FROM public.challenge_answers
  WHERE attempt_id = p_attempt_id AND is_correct = true;

  IF p_total_time_seconds IS NOT NULL AND p_total_time_seconds > 0 THEN
    v_time := p_total_time_seconds;
  ELSE
    v_time := EXTRACT(EPOCH FROM (now() - v_attempt.started_at))::int;
  END IF;

  IF v_challenge.duration_seconds > 0 AND v_time > (v_challenge.duration_seconds + 30) THEN
    v_time := v_challenge.duration_seconds;
  END IF;

  UPDATE public.challenge_attempts
  SET
    score = v_score,
    total_time_seconds = v_time,
    submitted_at = coalesce(submitted_at, now()),
    status = 'submitted'
  WHERE id = p_attempt_id;

  SELECT jsonb_agg(
    jsonb_build_object(
      'id', q.id,
      'order_index', q.order_index,
      'question_text', q.question_text,
      'choices', q.choices,
      'correct_choice', q.correct_choice,
      'explanation', coalesce(q.explanation_en, q.explanation, ''),
      'explanation_en', coalesce(q.explanation_en, q.explanation, ''),
      'explanation_am', coalesce(q.explanation_am, ''),
      'image_url', q.image_url,
      'passage_id', q.passage_id,
      'passage', CASE WHEN cp.id IS NOT NULL THEN jsonb_build_object(
        'id', -1,
        'title', cp.title,
        'content', cp.content,
        'image_url', cp.image_url
      ) ELSE NULL END
    ) ORDER BY q.order_index ASC
  ) INTO v_questions
  FROM public.challenge_questions q
  LEFT JOIN public.challenge_passages cp ON cp.id = q.passage_id
  WHERE (q.challenge_id = v_challenge.id
     OR (v_challenge.set_id IS NOT NULL AND q.set_id = v_challenge.set_id)
     OR q.set_id = v_challenge.id);

  RETURN jsonb_build_object(
    'success', true,
    'score', v_score,
    'total_time_seconds', v_time,
    'status', 'submitted',
    'questions', coalesce(v_questions, '[]'::jsonb)
  );
END;
$$;

-- Challenge RPC: Get Challenge Answers (Post-submission review)
CREATE OR REPLACE FUNCTION public.rpc_get_challenge_answers(
  p_challenge_id uuid
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_challenge record;
  v_questions jsonb;
  v_is_submitted boolean := false;
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'not_authenticated';
  END IF;

  SELECT * INTO v_challenge FROM public.leaderboard_challenges WHERE id = p_challenge_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'challenge_not_found';
  END IF;

  SELECT EXISTS (
    SELECT 1 FROM public.challenge_attempts
    WHERE challenge_id = p_challenge_id AND user_id = auth.uid() AND status = 'submitted'
  ) INTO v_is_submitted;

  IF NOT public.is_admin() AND v_challenge.status NOT IN ('closed', 'archived') AND NOT v_is_submitted THEN
    RAISE EXCEPTION 'challenge_answers_restricted';
  END IF;

  SELECT jsonb_agg(
    jsonb_build_object(
      'id', q.id,
      'challenge_id', q.challenge_id,
      'order_index', q.order_index,
      'question_text', q.question_text,
      'choices', q.choices,
      'correct_choice', q.correct_choice,
      'explanation', coalesce(q.explanation_en, q.explanation, ''),
      'explanation_en', coalesce(q.explanation_en, q.explanation, ''),
      'explanation_am', coalesce(q.explanation_am, ''),
      'image_url', q.image_url,
      'passage_id', q.passage_id,
      'passage', CASE WHEN cp.id IS NOT NULL THEN jsonb_build_object(
        'id', -1,
        'title', cp.title,
        'content', cp.content,
        'image_url', cp.image_url
      ) ELSE NULL END
    ) ORDER BY q.order_index ASC
  ) INTO v_questions
  FROM public.challenge_questions q
  LEFT JOIN public.challenge_passages cp ON cp.id = q.passage_id
  WHERE (q.challenge_id = v_challenge.id
     OR (v_challenge.set_id IS NOT NULL AND q.set_id = v_challenge.set_id)
     OR q.set_id = v_challenge.id);

  RETURN jsonb_build_object(
    'challenge_id', v_challenge.id,
    'subject_id', v_challenge.subject_id,
    'title', v_challenge.title,
    'audience', v_challenge.audience,
    'questions', coalesce(v_questions, '[]'::jsonb)
  );
END;
$$;

-- Challenge RPC: Get Real Participant Counts for Challenges
CREATE OR REPLACE FUNCTION public.rpc_get_challenge_participant_counts(
  p_challenge_ids uuid[] DEFAULT NULL
)
RETURNS TABLE (
  challenge_id uuid,
  participant_count bigint
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  IF p_challenge_ids IS NOT NULL AND array_length(p_challenge_ids, 1) > 0 THEN
    RETURN QUERY
    SELECT ca.challenge_id, count(*)::bigint
    FROM public.challenge_attempts ca
    WHERE ca.challenge_id = ANY(p_challenge_ids)
    GROUP BY ca.challenge_id;
  ELSE
    RETURN QUERY
    SELECT ca.challenge_id, count(*)::bigint
    FROM public.challenge_attempts ca
    GROUP BY ca.challenge_id;
  END IF;
END;
$$;

GRANT EXECUTE ON FUNCTION public.rpc_get_challenge_participant_counts TO authenticated;
GRANT EXECUTE ON FUNCTION public.rpc_get_challenge_participant_counts TO anon;

-- Challenge Leaderboard RPC (Cross-user standing with dense rank)
CREATE OR REPLACE FUNCTION public.rpc_get_leaderboard(
  p_challenge_id uuid,
  p_stream text DEFAULT NULL,
  p_limit int DEFAULT 100
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_rows jsonb;
  v_total_questions int := 0;
BEGIN
  -- Count total questions in this challenge
  SELECT count(*)::int INTO v_total_questions
  FROM public.challenge_questions
  WHERE challenge_id = p_challenge_id;

  IF v_total_questions = 0 THEN
    SELECT count(*)::int INTO v_total_questions
    FROM public.challenge_questions q
    JOIN public.leaderboard_challenges c ON c.set_id = q.set_id
    WHERE c.id = p_challenge_id;
  END IF;

  WITH ranked_attempts AS (
    SELECT
      ca.id AS attempt_id,
      ca.challenge_id,
      ca.user_id,
      coalesce(u.first_name, 'Student') AS first_name,
      coalesce(u.last_name, '') AS last_name,
      coalesce(ca.stream, u.stream, 'natural') AS stream,
      coalesce(ca.score, 0) AS score,
      coalesce(ca.total_time_seconds, ca.time_spent_seconds, 0) AS total_time_seconds,
      ca.submitted_at,
      DENSE_RANK() OVER (
        ORDER BY coalesce(ca.score, 0) DESC,
                 coalesce(ca.total_time_seconds, ca.time_spent_seconds, 0) ASC,
                 ca.submitted_at ASC
      ) AS rank
    FROM public.challenge_attempts ca
    LEFT JOIN public.users u ON u.id = ca.user_id
    WHERE ca.challenge_id = p_challenge_id
      AND ca.status = 'submitted'
      AND (
        p_stream IS NULL
        OR p_stream = ''
        OR lower(p_stream) = 'all'
        OR lower(p_stream) = 'both'
        OR lower(coalesce(ca.stream, u.stream, '')) = lower(p_stream)
      )
  )
  SELECT jsonb_agg(
    jsonb_build_object(
      'rank', r.rank,
      'user_id', r.user_id,
      'first_name', r.first_name,
      'last_name', r.last_name,
      'stream', r.stream,
      'score', r.score,
      'total_time_seconds', r.total_time_seconds,
      'correct_count', r.score,
      'incorrect_count', (
        SELECT count(*)::int FROM public.challenge_answers ans
        WHERE ans.attempt_id = r.attempt_id AND ans.is_correct = false
      ),
      'not_done_count', greatest(0, v_total_questions - (
        SELECT count(*)::int FROM public.challenge_answers ans
        WHERE ans.attempt_id = r.attempt_id
      )),
      'challenges_taken', 1
    ) ORDER BY r.rank ASC
  ) INTO v_rows
  FROM (
    SELECT * FROM ranked_attempts
    ORDER BY rank ASC
    LIMIT coalesce(p_limit, 100)
  ) r;

  RETURN coalesce(v_rows, '[]'::jsonb);
END;
$$;

-- Period Leaderboard RPC (Weekly / Monthly)
CREATE OR REPLACE FUNCTION public.rpc_get_period_leaderboard(
  p_stream text,
  p_period text, -- 'week' or 'month'
  p_period_start date DEFAULT NULL,
  p_limit int DEFAULT 100
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_rows jsonb;
  v_start date := p_period_start;
BEGIN
  IF v_start IS NULL THEN
    IF p_period = 'week' THEN
      v_start := date_trunc('week', now())::date;
    ELSE
      v_start := date_trunc('month', now())::date;
    END IF;
  END IF;

  WITH period_aggregated AS (
    SELECT
      ca.user_id,
      coalesce(u.first_name, 'Student') AS first_name,
      coalesce(u.last_name, '') AS last_name,
      coalesce(ca.stream, u.stream, 'natural') AS stream,
      sum(coalesce(ca.score, 0))::int AS total_score,
      sum(coalesce(ca.total_time_seconds, ca.time_spent_seconds, 0))::int AS total_time_seconds,
      count(ca.id)::int AS challenges_taken
    FROM public.challenge_attempts ca
    LEFT JOIN public.users u ON u.id = ca.user_id
    WHERE ca.status = 'submitted'
      AND ca.submitted_at >= v_start
      AND (
        p_stream IS NULL
        OR p_stream = ''
        OR lower(p_stream) = 'all'
        OR lower(p_stream) = 'both'
        OR lower(coalesce(ca.stream, u.stream, '')) = lower(p_stream)
      )
    GROUP BY ca.user_id, u.first_name, u.last_name, coalesce(ca.stream, u.stream, 'natural')
  ),
  ranked AS (
    SELECT
      pa.*,
      DENSE_RANK() OVER (
        ORDER BY pa.total_score DESC, pa.total_time_seconds ASC
      ) AS rank
    FROM period_aggregated pa
  )
  SELECT jsonb_agg(
    jsonb_build_object(
      'rank', r.rank,
      'user_id', r.user_id,
      'first_name', r.first_name,
      'last_name', r.last_name,
      'stream', r.stream,
      'score', r.total_score,
      'total_score', r.total_score,
      'total_time_seconds', r.total_time_seconds,
      'correct_count', r.total_score,
      'challenges_taken', r.challenges_taken,
      'period_start', v_start::text
    ) ORDER BY r.rank ASC
  ) INTO v_rows
  FROM (
    SELECT * FROM ranked
    ORDER BY rank ASC
    LIMIT coalesce(p_limit, 100)
  ) r;

  RETURN coalesce(v_rows, '[]'::jsonb);
END;
$$;

-- ─────────────────────────────────────────────────────────────────────
-- 11. ROW LEVEL SECURITY (RLS) POLICIES
-- ─────────────────────────────────────────────────────────────────────

-- Enable RLS across all tables
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admins ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admin_audit_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payment_receipts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payment_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notification_reads ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bookmarks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.test_attempts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.subjects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chapters ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.passages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.question_sections ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.app_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.leaderboard_challenges ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.challenge_question_sets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.challenge_passages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.challenge_questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.challenge_attempts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.challenge_answers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.challenge_rewards ENABLE ROW LEVEL SECURITY;

-- 11.1 Users policies
DROP POLICY IF EXISTS "Users can view own profile or admin" ON public.users;
CREATE POLICY "Users can view own profile or admin" ON public.users
    FOR SELECT USING (auth.uid() = id OR public.is_admin());

DROP POLICY IF EXISTS "Authenticated users view public profiles" ON public.users;
CREATE POLICY "Authenticated users view public profiles" ON public.users
    FOR SELECT TO authenticated
    USING (true);

DROP POLICY IF EXISTS "Users can update own profile or admin" ON public.users;
CREATE POLICY "Users can update own profile or admin" ON public.users
    FOR UPDATE USING (auth.uid() = id OR public.is_admin())
    WITH CHECK (auth.uid() = id OR public.is_admin());

DROP POLICY IF EXISTS "Users can insert own profile or admin" ON public.users;
CREATE POLICY "Users can insert own profile or admin" ON public.users
    FOR INSERT WITH CHECK (auth.uid() = id OR public.is_admin());

DROP POLICY IF EXISTS "Users can delete own profile or admin" ON public.users;
CREATE POLICY "Users can delete own profile or admin" ON public.users
    FOR DELETE USING (auth.uid() = id OR public.is_admin());

-- 11.2 User sessions policies
DROP POLICY IF EXISTS "Users can manage own session" ON public.user_sessions;
CREATE POLICY "Users can manage own session" ON public.user_sessions
    FOR ALL USING (auth.uid() = user_id OR public.is_admin())
    WITH CHECK (auth.uid() = user_id OR public.is_admin());

-- 11.3 Admins & audit policies
DROP POLICY IF EXISTS "Admins can view admins" ON public.admins;
CREATE POLICY "Admins can view admins" ON public.admins
    FOR SELECT USING (public.is_admin());

DROP POLICY IF EXISTS "Admins can manage admins" ON public.admins;
CREATE POLICY "Admins can manage admins" ON public.admins
    FOR ALL USING (public.is_admin())
    WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS "Admins can view audit log" ON public.admin_audit_log;
CREATE POLICY "Admins can view audit log" ON public.admin_audit_log
    FOR SELECT USING (public.is_admin());

DROP POLICY IF EXISTS "Admins can insert audit log" ON public.admin_audit_log;
CREATE POLICY "Admins can insert audit log" ON public.admin_audit_log
    FOR INSERT WITH CHECK (public.is_admin());

-- 11.4 Payment receipts & requests policies
DROP POLICY IF EXISTS "Users can view own receipts or admin" ON public.payment_receipts;
CREATE POLICY "Users can view own receipts or admin" ON public.payment_receipts
    FOR SELECT USING (auth.uid() = user_id OR public.is_admin());

DROP POLICY IF EXISTS "Users can insert own receipts" ON public.payment_receipts;
CREATE POLICY "Users can insert own receipts" ON public.payment_receipts
    FOR INSERT WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users or admins can delete own receipts" ON public.payment_receipts;
CREATE POLICY "Users or admins can delete own receipts" ON public.payment_receipts
    FOR DELETE USING (auth.uid() = user_id OR public.is_admin());

DROP POLICY IF EXISTS "Admins can update receipts" ON public.payment_receipts;
CREATE POLICY "Admins can update receipts" ON public.payment_receipts
    FOR UPDATE USING (public.is_admin())
    WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS "Users can view own payment requests or admin" ON public.payment_requests;
CREATE POLICY "Users can view own payment requests or admin" ON public.payment_requests
    FOR SELECT USING (auth.uid() = user_id OR public.is_admin());

DROP POLICY IF EXISTS "Users can insert own payment requests" ON public.payment_requests;
CREATE POLICY "Users can insert own payment requests" ON public.payment_requests
    FOR INSERT WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users or admins can delete own payment requests" ON public.payment_requests;
CREATE POLICY "Users or admins can delete own payment requests" ON public.payment_requests
    FOR DELETE USING (auth.uid() = user_id OR public.is_admin());

DROP POLICY IF EXISTS "Admins can update payment requests" ON public.payment_requests;
CREATE POLICY "Admins can update payment requests" ON public.payment_requests
    FOR UPDATE USING (public.is_admin())
    WITH CHECK (public.is_admin());

-- 11.5 Notifications policies
DROP POLICY IF EXISTS "Users can view targeted or broadcast notifications" ON public.notifications;
CREATE POLICY "Users can view targeted or broadcast notifications" ON public.notifications
    FOR SELECT USING (user_id IS NULL OR auth.uid() = user_id OR public.is_admin());

DROP POLICY IF EXISTS "Admins can manage notifications" ON public.notifications;
CREATE POLICY "Admins can manage notifications" ON public.notifications
    FOR ALL USING (public.is_admin())
    WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS "Users can manage own notification reads" ON public.notification_reads;
CREATE POLICY "Users can manage own notification reads" ON public.notification_reads
    FOR ALL USING (auth.uid() = user_id OR public.is_admin())
    WITH CHECK (auth.uid() = user_id OR public.is_admin());

-- 11.6 Bookmarks & Test Attempts
DROP POLICY IF EXISTS "Users can manage own bookmarks" ON public.bookmarks;
CREATE POLICY "Users can manage own bookmarks" ON public.bookmarks
    FOR ALL USING (auth.uid() = user_id OR public.is_admin())
    WITH CHECK (auth.uid() = user_id OR public.is_admin());

DROP POLICY IF EXISTS "Users can view own test attempts" ON public.test_attempts;
CREATE POLICY "Users can view own test attempts" ON public.test_attempts
    FOR SELECT USING (auth.uid() = user_id OR public.is_admin());

DROP POLICY IF EXISTS "Users can insert own test attempts" ON public.test_attempts;
CREATE POLICY "Users can insert own test attempts" ON public.test_attempts
    FOR INSERT WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can delete own test attempts" ON public.test_attempts;
CREATE POLICY "Users can delete own test attempts" ON public.test_attempts
    FOR DELETE USING (auth.uid() = user_id OR public.is_admin());

-- 11.7 Public educational content (Public read, admin-only write)
DROP POLICY IF EXISTS "Subjects are publicly readable" ON public.subjects;
CREATE POLICY "Subjects are publicly readable" ON public.subjects FOR SELECT USING (true);
DROP POLICY IF EXISTS "Admins manage subjects" ON public.subjects;
CREATE POLICY "Admins manage subjects" ON public.subjects FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS "Chapters are publicly readable" ON public.chapters;
CREATE POLICY "Chapters are publicly readable" ON public.chapters FOR SELECT USING (true);
DROP POLICY IF EXISTS "Admins manage chapters" ON public.chapters;
CREATE POLICY "Admins manage chapters" ON public.chapters FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS "Passages are publicly readable" ON public.passages;
CREATE POLICY "Passages are publicly readable" ON public.passages FOR SELECT USING (true);
DROP POLICY IF EXISTS "Admins manage passages" ON public.passages;
CREATE POLICY "Admins manage passages" ON public.passages FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS "Question sections are publicly readable" ON public.question_sections;
CREATE POLICY "Question sections are publicly readable" ON public.question_sections FOR SELECT USING (true);
DROP POLICY IF EXISTS "Admins manage question sections" ON public.question_sections;
CREATE POLICY "Admins manage question sections" ON public.question_sections FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS "Tests are publicly readable" ON public.tests;
CREATE POLICY "Tests are publicly readable" ON public.tests FOR SELECT USING (true);
DROP POLICY IF EXISTS "Admins manage tests" ON public.tests;
CREATE POLICY "Admins manage tests" ON public.tests FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS "Questions are publicly readable" ON public.questions;
CREATE POLICY "Questions are publicly readable" ON public.questions FOR SELECT USING (true);
DROP POLICY IF EXISTS "Admins manage questions" ON public.questions;
CREATE POLICY "Admins manage questions" ON public.questions FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS "App config is publicly readable" ON public.app_config;
CREATE POLICY "App config is publicly readable" ON public.app_config FOR SELECT USING (true);
DROP POLICY IF EXISTS "Admins manage app config" ON public.app_config;
CREATE POLICY "Admins manage app config" ON public.app_config FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());

-- 11.8 Challenge subsystem policies (Anti-cheating & privacy)
DROP POLICY IF EXISTS "Leaderboard challenges view policy" ON public.leaderboard_challenges;
CREATE POLICY "Leaderboard challenges view policy" ON public.leaderboard_challenges
    FOR SELECT TO authenticated
    USING (public.is_admin() OR status IN ('scheduled', 'live', 'closed', 'archived'));

DROP POLICY IF EXISTS "Admins manage leaderboard challenges" ON public.leaderboard_challenges;
CREATE POLICY "Admins manage leaderboard challenges" ON public.leaderboard_challenges
    FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS "Challenge question sets view policy" ON public.challenge_question_sets;
CREATE POLICY "Challenge question sets view policy" ON public.challenge_question_sets
    FOR SELECT TO authenticated
    USING (public.is_admin() OR EXISTS (
        SELECT 1 FROM public.leaderboard_challenges lc
        WHERE lc.set_id = challenge_question_sets.id
          AND lc.status IN ('scheduled', 'live', 'closed', 'archived')
    ));

DROP POLICY IF EXISTS "Admins manage challenge question sets" ON public.challenge_question_sets;
CREATE POLICY "Admins manage challenge question sets" ON public.challenge_question_sets
    FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS "Challenge passages view policy" ON public.challenge_passages;
CREATE POLICY "Challenge passages view policy" ON public.challenge_passages
    FOR SELECT TO authenticated
    USING (public.is_admin() OR EXISTS (
        SELECT 1 FROM public.challenge_questions cq
        JOIN public.challenge_question_sets cqs ON cqs.id = cq.set_id
        JOIN public.leaderboard_challenges lc ON lc.set_id = cqs.id
        WHERE cq.passage_id = challenge_passages.id
          AND lc.status IN ('scheduled', 'live', 'closed', 'archived')
    ));

DROP POLICY IF EXISTS "Admins manage challenge passages" ON public.challenge_passages;
CREATE POLICY "Admins manage challenge passages" ON public.challenge_passages
    FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS "Challenge questions view policy" ON public.challenge_questions;
CREATE POLICY "Challenge questions view policy" ON public.challenge_questions
    FOR SELECT TO authenticated
    USING (
        public.is_admin()
        OR EXISTS (
            SELECT 1 FROM public.leaderboard_challenges lc
            WHERE lc.id = challenge_questions.challenge_id
              AND (
                lc.status IN ('closed', 'archived')
                OR EXISTS (
                    SELECT 1 FROM public.challenge_attempts a
                    WHERE a.challenge_id = lc.id
                      AND a.user_id = auth.uid()
                      AND a.status = 'submitted'
                )
              )
        )
        OR EXISTS (
            SELECT 1 FROM public.challenge_question_sets cqs
            JOIN public.leaderboard_challenges lc ON lc.set_id = cqs.id
            WHERE cqs.id = challenge_questions.set_id
              AND (
                lc.status IN ('closed', 'archived')
                OR EXISTS (
                    SELECT 1 FROM public.challenge_attempts a
                    WHERE a.challenge_id = lc.id
                      AND a.user_id = auth.uid()
                      AND a.status = 'submitted'
                )
              )
        )
    );

DROP POLICY IF EXISTS "Admins manage challenge questions" ON public.challenge_questions;
CREATE POLICY "Admins manage challenge questions" ON public.challenge_questions
    FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS "Users can view own or submitted attempts" ON public.challenge_attempts;
CREATE POLICY "Users can view own or submitted attempts" ON public.challenge_attempts
    FOR SELECT TO authenticated
    USING (auth.uid() = user_id OR status = 'submitted' OR public.is_admin());

DROP POLICY IF EXISTS "Users can insert own challenge attempts" ON public.challenge_attempts;
CREATE POLICY "Users can insert own challenge attempts" ON public.challenge_attempts
    FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update own challenge attempts" ON public.challenge_attempts;
CREATE POLICY "Users can update own challenge attempts" ON public.challenge_attempts
    FOR UPDATE TO authenticated
    USING (auth.uid() = user_id OR public.is_admin())
    WITH CHECK (auth.uid() = user_id OR public.is_admin());

DROP POLICY IF EXISTS "Users can delete own challenge attempts" ON public.challenge_attempts;
CREATE POLICY "Users can delete own challenge attempts" ON public.challenge_attempts
    FOR DELETE TO authenticated USING (auth.uid() = user_id OR public.is_admin());

DROP POLICY IF EXISTS "Users can view own challenge answers" ON public.challenge_answers;
CREATE POLICY "Users can view own challenge answers" ON public.challenge_answers
    FOR SELECT TO authenticated
    USING (EXISTS (
        SELECT 1 FROM public.challenge_attempts a
        WHERE a.id = challenge_answers.attempt_id
          AND (a.user_id = auth.uid() OR public.is_admin())
    ));

DROP POLICY IF EXISTS "Users can insert own challenge answers" ON public.challenge_answers;
CREATE POLICY "Users can insert own challenge answers" ON public.challenge_answers
    FOR INSERT TO authenticated
    WITH CHECK (EXISTS (
        SELECT 1 FROM public.challenge_attempts a
        WHERE a.id = challenge_answers.attempt_id
          AND a.user_id = auth.uid()
          AND a.status = 'in_progress'
    ));

DROP POLICY IF EXISTS "Users can update own challenge answers" ON public.challenge_answers;
CREATE POLICY "Users can update own challenge answers" ON public.challenge_answers
    FOR UPDATE TO authenticated
    USING (EXISTS (
        SELECT 1 FROM public.challenge_attempts a
        WHERE a.id = challenge_answers.attempt_id
          AND (a.user_id = auth.uid() OR public.is_admin())
          AND (a.status = 'in_progress' OR public.is_admin())
    ))
    WITH CHECK (EXISTS (
        SELECT 1 FROM public.challenge_attempts a
        WHERE a.id = challenge_answers.attempt_id
          AND (a.user_id = auth.uid() OR public.is_admin())
          AND (a.status = 'in_progress' OR public.is_admin())
    ));

DROP POLICY IF EXISTS "Users can delete own challenge answers" ON public.challenge_answers;
CREATE POLICY "Users can delete own challenge answers" ON public.challenge_answers
    FOR DELETE TO authenticated
    USING (EXISTS (
        SELECT 1 FROM public.challenge_attempts a
        WHERE a.id = challenge_answers.attempt_id
          AND (a.user_id = auth.uid() OR public.is_admin())
    ));

DROP POLICY IF EXISTS "Challenge rewards view policy" ON public.challenge_rewards;
CREATE POLICY "Challenge rewards view policy" ON public.challenge_rewards
    FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "Admins can manage challenge rewards" ON public.challenge_rewards;
CREATE POLICY "Admins can manage challenge rewards" ON public.challenge_rewards
    FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());

-- 11.9 Storage bucket RLS policies for 'receipts'
DROP POLICY IF EXISTS "Students can upload receipts to own folder" ON storage.objects;
CREATE POLICY "Students can upload receipts to own folder" ON storage.objects
    FOR INSERT TO authenticated
    WITH CHECK (
        bucket_id = 'receipts'
        AND (auth.uid())::text = (storage.foldername(name))[1]
    );

DROP POLICY IF EXISTS "Students can view own receipts or admin" ON storage.objects;
CREATE POLICY "Students can view own receipts or admin" ON storage.objects
    FOR SELECT TO authenticated
    USING (
        bucket_id = 'receipts'
        AND (
            (auth.uid())::text = (storage.foldername(name))[1]
            OR public.is_admin()
        )
    );

DROP POLICY IF EXISTS "Students can delete own receipts or admin" ON storage.objects;
CREATE POLICY "Students can delete own receipts or admin" ON storage.objects
    FOR DELETE TO authenticated
    USING (
        bucket_id = 'receipts'
        AND (
            (auth.uid())::text = (storage.foldername(name))[1]
            OR public.is_admin()
        )
    );

-- ─────────────────────────────────────────────────────────────────────
-- 12. REALTIME REPLICA IDENTITIES
-- ─────────────────────────────────────────────────────────────────────

ALTER TABLE public.app_config             REPLICA IDENTITY FULL;
ALTER TABLE public.notifications          REPLICA IDENTITY FULL;
ALTER TABLE public.notification_reads     REPLICA IDENTITY FULL;
ALTER TABLE public.users                  REPLICA IDENTITY FULL;
ALTER TABLE public.user_sessions          REPLICA IDENTITY FULL;
ALTER TABLE public.leaderboard_challenges REPLICA IDENTITY FULL;
ALTER TABLE public.challenge_attempts     REPLICA IDENTITY FULL;
ALTER TABLE public.challenge_rewards      REPLICA IDENTITY FULL;

COMMIT;
