-- 0005_single_device_security_and_audit.sql
-- Single-device enforcement, device metadata, audit trail, and admin device reset.

-- 1. Alter public.user_sessions to support null device_id (unlocked state) and metadata
ALTER TABLE public.user_sessions ALTER COLUMN device_id DROP NOT NULL;
ALTER TABLE public.user_sessions ADD COLUMN IF NOT EXISTS device_model text;
ALTER TABLE public.user_sessions ADD COLUMN IF NOT EXISTS os_version text;
ALTER TABLE public.user_sessions ADD COLUMN IF NOT EXISTS last_active_at timestamptz DEFAULT now();

-- 2. Create public.device_history table
CREATE TABLE IF NOT EXISTS public.device_history (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    action       text NOT NULL, -- 'INITIAL_BIND', 'ADMIN_RESET', 'BLOCKED_ATTEMPT'
    device_id    text,
    device_model text,
    os_version   text,
    performed_by text NOT NULL, -- 'USER', 'SYSTEM', or admin UID / email
    note         text,
    created_at   timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS device_history_user_created_idx ON public.device_history (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS device_history_action_idx ON public.device_history (action);

-- Enable RLS on device_history
ALTER TABLE public.device_history ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Admins can view device history" ON public.device_history;
CREATE POLICY "Admins can view device history" ON public.device_history
    FOR SELECT USING (public.is_admin());

DROP POLICY IF EXISTS "Users can view own device history" ON public.device_history;
CREATE POLICY "Users can view own device history" ON public.device_history
    FOR SELECT USING (auth.uid() = user_id);

-- 3. Secure RPC: bind_user_device
CREATE OR REPLACE FUNCTION public.bind_user_device(
    p_device_id text,
    p_device_model text DEFAULT NULL,
    p_os_version text DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    v_uid uuid := auth.uid();
    v_session record;
    v_user_email text;
BEGIN
    IF v_uid IS NULL THEN
        RAISE EXCEPTION 'Authentication required';
    END IF;

    -- Reviewer & test account bypass check: automatically rebinds and allows without restrictions
    SELECT COALESCE(
        (SELECT email FROM auth.users WHERE id = v_uid LIMIT 1),
        (SELECT email FROM public.users WHERE id = v_uid LIMIT 1)
    ) INTO v_user_email;

    IF lower(trim(COALESCE(v_user_email, ''))) = 'yeabrom@gmail.com' THEN
        INSERT INTO public.user_sessions (user_id, device_id, device_model, os_version, last_active_at, updated_at)
        VALUES (v_uid, p_device_id, p_device_model, p_os_version, now(), now())
        ON CONFLICT (user_id) DO UPDATE
        SET device_id = EXCLUDED.device_id,
            device_model = EXCLUDED.device_model,
            os_version = EXCLUDED.os_version,
            last_active_at = now(),
            updated_at = now();

        RETURN jsonb_build_object('status', 'allowed', 'message', 'Whitelisted test account');
    END IF;

    SELECT * INTO v_session FROM public.user_sessions WHERE user_id = v_uid;

    -- Scenario A: No session exists yet, or device was reset by admin (device_id IS NULL)
    IF v_session IS NULL OR v_session.device_id IS NULL THEN
        INSERT INTO public.user_sessions (user_id, device_id, device_model, os_version, last_active_at, updated_at)
        VALUES (v_uid, p_device_id, p_device_model, p_os_version, now(), now())
        ON CONFLICT (user_id) DO UPDATE
        SET device_id = EXCLUDED.device_id,
            device_model = EXCLUDED.device_model,
            os_version = EXCLUDED.os_version,
            last_active_at = now(),
            updated_at = now();

        -- Record initial binding in history
        INSERT INTO public.device_history (
            user_id, action, device_id, device_model, os_version, performed_by, note
        ) VALUES (
            v_uid, 'INITIAL_BIND', p_device_id, p_device_model, p_os_version, 'USER', 'Device bound to account'
        );

        RETURN jsonb_build_object(
            'status', 'allowed',
            'message', 'Device registered successfully'
        );
    END IF;

    -- Scenario B: Same device logging in or active
    IF v_session.device_id = p_device_id THEN
        UPDATE public.user_sessions
        SET last_active_at = now(),
            device_model = COALESCE(p_device_model, device_model),
            os_version = COALESCE(p_os_version, os_version),
            updated_at = now()
        WHERE user_id = v_uid;

        RETURN jsonb_build_object(
            'status', 'allowed',
            'message', 'Device verified'
        );
    END IF;

    -- Scenario C: Mismatch - different device attempted login!
    INSERT INTO public.device_history (
        user_id, action, device_id, device_model, os_version, performed_by, note
    ) VALUES (
        v_uid,
        'BLOCKED_ATTEMPT',
        p_device_id,
        p_device_model,
        p_os_version,
        'SYSTEM',
        'Attempted login from unauthorized device while locked to ' || COALESCE(v_session.device_model, 'registered device')
    );

    RETURN jsonb_build_object(
        'status', 'blocked',
        'message', 'Account is registered on another device',
        'bound_device', v_session.device_model
    );
END;
$$;

-- 4. Secure RPC: admin_reset_user_device
CREATE OR REPLACE FUNCTION public.admin_reset_user_device(
    p_user_id uuid,
    p_admin_uid text,
    p_reason text DEFAULT NULL
)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    v_old_session record;
BEGIN
    -- Verify caller is admin
    IF NOT public.is_admin() THEN
        RAISE EXCEPTION 'Unauthorized: only admins can reset user devices';
    END IF;

    SELECT * INTO v_old_session FROM public.user_sessions WHERE user_id = p_user_id;

    -- Clear device_id
    UPDATE public.user_sessions
    SET device_id = NULL,
        updated_at = now()
    WHERE user_id = p_user_id;

    IF NOT FOUND THEN
        INSERT INTO public.user_sessions (user_id, device_id, updated_at)
        VALUES (p_user_id, NULL, now());
    END IF;

    -- Log to device_history
    INSERT INTO public.device_history (
        user_id, action, device_id, device_model, os_version, performed_by, note
    ) VALUES (
        p_user_id,
        'ADMIN_RESET',
        v_old_session.device_id,
        v_old_session.device_model,
        v_old_session.os_version,
        p_admin_uid,
        p_reason
    );

    -- Log to admin_audit_log
    INSERT INTO public.admin_audit_log (
        admin_uid, action, entity_type, entity_id, before, after, note
    ) VALUES (
        p_admin_uid,
        'RESET_DEVICE',
        'user_session',
        p_user_id::text,
        jsonb_build_object('device_id', v_old_session.device_id, 'device_model', v_old_session.device_model),
        jsonb_build_object('device_id', NULL),
        p_reason
    );

    RETURN true;
END;
$$;

-- 5. Update user_sessions RLS policies
DROP POLICY IF EXISTS "Users can manage own session" ON public.user_sessions;
DROP POLICY IF EXISTS "Users can view own session or admin" ON public.user_sessions;
CREATE POLICY "Users can view own session or admin" ON public.user_sessions
    FOR SELECT USING (auth.uid() = user_id OR public.is_admin());

DROP POLICY IF EXISTS "Admins can manage sessions" ON public.user_sessions;
CREATE POLICY "Admins can manage sessions" ON public.user_sessions
    FOR ALL USING (public.is_admin())
    WITH CHECK (public.is_admin());
